name: Python clashproxy update

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
        
    - name: Update proxy lists
      run: |
        python main.py
        
    - name: commit
      run: |
        git config --global user.email chaoranzhi@gmail.com
        git config --global user.name chaoranzhi
        git add .
        git commit -m "update" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ 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 }}
