name: Python clashproxy update

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * *"
    # 每天伦敦时间2点执行，对应北京时间10点
jobs:
  build:
    # 指定一下任务运行的系统环境
    runs-on: ubuntu-latest

 
    steps:
    - name: checkout actions
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    
    # run: 后面添加你自己要执行的命令，如果有多条命令，用|换行。如果只有一行命令，可以直接写作run: 后面
    - name: Update proxy lists
      run: |
        python main.py
        
    - name: commit
      run: |
        git config --global user.email 1917984861@qq.com
        git config --global user.name chaoranzhi
        git add .
        git commit -m "update" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
